# Generated by Django 5.2.9 on 2026-09-26 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Unofficial Freshers '26", max_length=120)),
                ('event_date', models.DateTimeField(default='2026-10-10T18:00:00+05:30')),
                ('venue', models.CharField(default='Bonvivant Banquet Hall, City Center', max_length=180)),
                ('ticket_price', models.PositiveIntegerField(default=750)),
                ('capacity', models.PositiveIntegerField(default=120)),
                ('upi_id', models.CharField(default='engineering.freshers@upi', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('participants', models.JSONField(default=list)),
                ('ticket_quantity', models.PositiveSmallIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('utr_number', models.CharField(max_length=40)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
