# Generated by Django 5.2.9 on 2026-09-26 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def migrate_registrations(apps, schema_editor):
        Registration = apps.get_model('eventsite', 'Registration')
        Payment = apps.get_model('eventsite', 'Payment')
        Ticket = apps.get_model('eventsite', 'Ticket')
        database = schema_editor.connection.alias

        for registration in Registration.objects.using(database).all().iterator():
            Payment.objects.using(database).create(
                registration_id=registration.pk,
                utr_number=registration.utr_number,
                amount=registration.total_amount,
                status=registration.payment_status,
            )
            for attendee in registration.participants:
                Ticket.objects.using(database).create(
                    registration_id=registration.pk,
                    attendee_name=str(attendee.get('name', ''))[:100],
                    department=str(attendee.get('department', ''))[:80],
                    year=str(attendee.get('year', ''))[:40],
                    phone=str(attendee.get('phone', ''))[:10],
                    email=str(attendee.get('email', ''))[:254],
                )

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utr_number', models.CharField(max_length=40, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='eventsite.registration')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_freshers_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attendee_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=80)),
                ('year', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_freshers_tickets', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='eventsite.registration')),
            ],
            options={
                'indexes': [models.Index(fields=['registration', 'checked_in_at'], name='eventsite_t_registr_8d8dbe_idx')],
            },
        ),
        migrations.RunPython(migrate_registrations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='registration',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='utr_number',
        ),
    ]
