# Generated by Django 5.2.9 on 2026-09-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0003_eventcontact_eventfaq_eventrule_eventvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='organizer_name',
            field=models.CharField(default='Department of Engineering', max_length=120),
        ),
    ]
