# Generated by Django 5.2.9 on 2026-09-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0004_eventsettings_organizer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvideo',
            name='source_type',
            field=models.CharField(choices=[('YOUTUBE', 'External video URL (YouTube / Reel)'), ('UPLOAD', 'Uploaded video')], default='YOUTUBE', max_length=10),
        ),
    ]
