# Generated by Django 5.2.9 on 2026-09-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0006_galleryimage_image_url_alter_galleryimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('responses', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Google Form response',
                'verbose_name_plural': 'Google Form responses',
                'ordering': ['-submitted_at', '-received_at'],
            },
        ),
    ]
