# Generated by Django 5.2.9 on 2026-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0007_googleformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='event_end_time',
            field=models.TimeField(default='18:00', verbose_name='Event end time'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='event_date',
            field=models.DateTimeField(default='2026-10-10T11:00:00+05:30'),
        ),
    ]
