# Generated by Django 5.2.9 on 2026-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0008_eventsettings_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvideo',
            name='edition',
            field=models.CharField(choices=[('PREVIOUS', "Last year's party"), ('CURRENT', "This year's party"), ('PROMO', 'Promo / teaser')], default='PROMO', max_length=8),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='collection',
            field=models.CharField(choices=[('GENERAL', 'General gallery'), ('PREVIOUS', "Last year's party"), ('VENUE', "This year's venue")], default='GENERAL', max_length=12),
        ),
    ]
