# Generated by Django 5.2.9 on 2026-09-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0009_eventvideo_edition_galleryimage_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastYearLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'past year link',
                'verbose_name_plural': 'past year links',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
